// Sample data for demo purposes when Supabase credentials are not available

export const sampleProducts = [
  {
    id: "1",
    title: "Calculus Textbook - 10th Edition",
    description: "Barely used calculus textbook. Perfect condition with no markings. Great for MATH 101.",
    price: 45,
    category: "Books",
    status: "available",
    image_url: null,
    created_at: "2024-01-15T10:00:00Z",
    seller: {
      id: "user1",
      full_name: "Sarah Johnson",
      avatar_url: null,
    },
  },
  {
    id: "2",
    title: "MacBook Pro 2020 - 13 inch",
    description: "Selling my MacBook Pro. 16GB RAM, 512GB SSD. Excellent condition, comes with charger.",
    price: 800,
    category: "Electronics",
    status: "available",
    image_url: null,
    created_at: "2024-01-14T15:30:00Z",
    seller: {
      id: "user2",
      full_name: "Mike Chen",
      avatar_url: null,
    },
  },
  {
    id: "3",
    title: "Study Desk with Chair",
    description: "Wooden study desk with matching chair. Perfect for dorm room. Dimensions: 120x60cm.",
    price: 75,
    category: "Furniture",
    status: "available",
    image_url: null,
    created_at: "2024-01-13T09:15:00Z",
    seller: {
      id: "user3",
      full_name: "Emma Davis",
      avatar_url: null,
    },
  },
  {
    id: "4",
    title: "Scientific Calculator TI-84",
    description: "TI-84 Plus graphing calculator. Works perfectly, includes USB cable and manual.",
    price: 60,
    category: "Electronics",
    status: "available",
    image_url: null,
    created_at: "2024-01-12T14:20:00Z",
    seller: {
      id: "user4",
      full_name: "James Wilson",
      avatar_url: null,
    },
  },
  {
    id: "5",
    title: "Mini Fridge - Compact",
    description: "Small fridge perfect for dorm. Energy efficient, barely used. 1.7 cubic feet.",
    price: 90,
    category: "Furniture",
    status: "available",
    image_url: null,
    created_at: "2024-01-11T11:45:00Z",
    seller: {
      id: "user5",
      full_name: "Lisa Anderson",
      avatar_url: null,
    },
  },
  {
    id: "6",
    title: "Chemistry Lab Coat",
    description: "White lab coat, size M. Required for CHEM 201. Only worn a few times.",
    price: 15,
    category: "Clothing",
    status: "available",
    image_url: null,
    created_at: "2024-01-10T16:00:00Z",
    seller: {
      id: "user6",
      full_name: "Tom Martinez",
      avatar_url: null,
    },
  },
]

export const sampleServices = [
  {
    id: "1",
    title: "Math Tutoring - Calculus & Algebra",
    description: "Experienced tutor offering help with calculus, algebra, and statistics. A+ student in all math courses.",
    price: 25,
    price_type: "hourly",
    category: "Tutoring",
    is_available: true,
    rating: 4.8,
    total_bookings: 23,
    images: [],
    created_at: "2024-01-15T10:00:00Z",
    provider: {
      id: "user7",
      full_name: "Alex Thompson",
      avatar_url: null,
    },
  },
  {
    id: "2",
    title: "Graphic Design Services",
    description: "Professional logo design, posters, and social media graphics. Portfolio available upon request.",
    price: 30,
    price_type: "hourly",
    category: "Design",
    is_available: true,
    rating: 4.9,
    total_bookings: 18,
    images: [],
    created_at: "2024-01-14T12:30:00Z",
    provider: {
      id: "user8",
      full_name: "Maya Patel",
      avatar_url: null,
    },
  },
  {
    id: "3",
    title: "Essay Proofreading & Editing",
    description: "English major offering proofreading and editing services. Quick turnaround, attention to detail.",
    price: 20,
    price_type: "hourly",
    category: "Writing",
    is_available: true,
    rating: 4.7,
    total_bookings: 31,
    images: [],
    created_at: "2024-01-13T14:15:00Z",
    provider: {
      id: "user9",
      full_name: "Rachel Green",
      avatar_url: null,
    },
  },
  {
    id: "4",
    title: "Web Development - React & Node.js",
    description: "Full-stack developer available for web projects. Experienced with React, Node.js, and databases.",
    price: 40,
    price_type: "hourly",
    category: "Programming",
    is_available: true,
    rating: 5.0,
    total_bookings: 15,
    images: [],
    created_at: "2024-01-12T09:45:00Z",
    provider: {
      id: "user10",
      full_name: "David Kim",
      avatar_url: null,
    },
  },
  {
    id: "5",
    title: "Photography for Events",
    description: "Professional event photography. Parties, graduations, club events. Includes editing.",
    price: 50,
    price_type: "hourly",
    category: "Photography",
    is_available: true,
    rating: 4.6,
    total_bookings: 12,
    images: [],
    created_at: "2024-01-11T16:20:00Z",
    provider: {
      id: "user11",
      full_name: "Sophie Brown",
      avatar_url: null,
    },
  },
  {
    id: "6",
    title: "Spanish Language Tutoring",
    description: "Native Spanish speaker offering conversational practice and grammar help. All levels welcome.",
    price: 22,
    price_type: "hourly",
    category: "Tutoring",
    is_available: true,
    rating: 4.8,
    total_bookings: 27,
    images: [],
    created_at: "2024-01-10T13:00:00Z",
    provider: {
      id: "user12",
      full_name: "Carlos Rodriguez",
      avatar_url: null,
    },
  },
]

export const sampleRequests = [
  {
    id: "1",
    title: "Need Biology Notes from Last Week",
    description: "Missed BIO 201 lectures last week due to illness. Would really appreciate if someone could share notes!",
    category: "Academic",
    urgency: "high",
    status: "open",
    created_at: "2024-01-15T08:00:00Z",
    requester: {
      id: "user13",
      full_name: "Jessica Lee",
      avatar_url: null,
    },
  },
  {
    id: "2",
    title: "Looking for Ride to Airport",
    description: "Need a ride to the airport this Friday at 6 AM. Will pay for gas + extra. Going to LAX.",
    category: "Transportation",
    urgency: "urgent",
    status: "open",
    created_at: "2024-01-14T19:30:00Z",
    requester: {
      id: "user14",
      full_name: "Kevin Zhang",
      avatar_url: null,
    },
  },
  {
    id: "3",
    title: "Help Moving Furniture",
    description: "Moving to a new dorm this weekend. Need 2-3 people to help move furniture. Pizza provided!",
    category: "Other",
    urgency: "medium",
    status: "open",
    created_at: "2024-01-13T15:45:00Z",
    requester: {
      id: "user15",
      full_name: "Amanda White",
      avatar_url: null,
    },
  },
  {
    id: "4",
    title: "Borrowing Textbook for Weekend",
    description: "Need to borrow 'Introduction to Psychology' textbook for the weekend to study for exam. Will return Monday!",
    category: "Academic",
    urgency: "high",
    status: "open",
    created_at: "2024-01-12T11:20:00Z",
    requester: {
      id: "user16",
      full_name: "Ryan Cooper",
      avatar_url: null,
    },
  },
  {
    id: "5",
    title: "Study Group for Physics Exam",
    description: "Looking for 3-4 students to form a study group for the upcoming Physics 101 midterm. Let's ace this!",
    category: "Academic",
    urgency: "medium",
    status: "open",
    created_at: "2024-01-11T10:00:00Z",
    requester: {
      id: "user17",
      full_name: "Olivia Taylor",
      avatar_url: null,
    },
  },
  {
    id: "6",
    title: "Lost Laptop Charger - Urgent!",
    description: "Lost my MacBook charger somewhere on campus. Desperately need to borrow one for a few hours to finish assignment!",
    category: "Other",
    urgency: "urgent",
    status: "open",
    created_at: "2024-01-10T17:30:00Z",
    requester: {
      id: "user18",
      full_name: "Daniel Harris",
      avatar_url: null,
    },
  },
]
